"""initial migration

Revision ID: 097fe1bb4e40
Revises: 
Create Date: 2023-01-16 21:39:55.001698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097fe1bb4e40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    # ### end Alembic commands ###
